version: '3'
services:
  web:
    build: .
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres:5432/postcode-service
      - DATABASE_POOL_SIZE=15
    ports:
      - 3000:3000

  postgres:
    image: mdillon/postgis
    environment:
      - POSTGRES_DB=postcode-service
      - POSTGRES_PASSWORD=password
